/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DisparoRouteImport } from './routes/disparo'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as EmpresasIdRouteImport } from './routes/empresas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparoRoute = DisparoRouteImport.update({
  id: '/disparo',
  path: '/disparo',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIdRoute = EmpresasIdRouteImport.update({
  id: '/empresas/$id',
  path: '/empresas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparo': typeof DisparoRoute
  '/followups': typeof FollowupsRoute
  '/mapa': typeof MapaRoute
  '/mensagens': typeof MensagensRoute
  '/propostas': typeof PropostasRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparo': typeof DisparoRoute
  '/followups': typeof FollowupsRoute
  '/mapa': typeof MapaRoute
  '/mensagens': typeof MensagensRoute
  '/propostas': typeof PropostasRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/empresas': typeof EmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparo': typeof DisparoRoute
  '/followups': typeof FollowupsRoute
  '/mapa': typeof MapaRoute
  '/mensagens': typeof MensagensRoute
  '/propostas': typeof PropostasRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/disparo'
    | '/followups'
    | '/mapa'
    | '/mensagens'
    | '/propostas'
    | '/prospeccao'
    | '/relatorios'
    | '/empresas/$id'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/disparo'
    | '/followups'
    | '/mapa'
    | '/mensagens'
    | '/propostas'
    | '/prospeccao'
    | '/relatorios'
    | '/empresas/$id'
    | '/empresas'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/disparo'
    | '/followups'
    | '/mapa'
    | '/mensagens'
    | '/propostas'
    | '/prospeccao'
    | '/relatorios'
    | '/empresas/$id'
    | '/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DisparoRoute: typeof DisparoRoute
  FollowupsRoute: typeof FollowupsRoute
  MapaRoute: typeof MapaRoute
  MensagensRoute: typeof MensagensRoute
  PropostasRoute: typeof PropostasRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  EmpresasIdRoute: typeof EmpresasIdRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparo': {
      id: '/disparo'
      path: '/disparo'
      fullPath: '/disparo'
      preLoaderRoute: typeof DisparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$id': {
      id: '/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof EmpresasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DisparoRoute: DisparoRoute,
  FollowupsRoute: FollowupsRoute,
  MapaRoute: MapaRoute,
  MensagensRoute: MensagensRoute,
  PropostasRoute: PropostasRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  EmpresasIdRoute: EmpresasIdRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
