// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcdmaohrbvafqkgqnrux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZG1hb2hyYnZhZnFrZ3FucnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwNDIxMzQsImV4cCI6MjEwMjYxODEzNH0.fxjpCZUkEqZohjWXfpfN1OXi3r4o3ILl6WShLnKDpAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});